const fs = require('fs');

const translations = {
  "Giancarlo Morbidelli: Legendary Constructor of Racing Motorcycles": "Đankarlo Morbideli: Legendarni konstruktor trkačkih motocikala",
  "In 1972, the development of the Morbidelli 50cc models was halted due to the Reparto Corse's focus on developing the 125cc category. Gilberto Parlotti was unstoppable with four consecutive victories in the 125cc class, but at the height of his progress, tragedy struck the Morbidelli team. While leading the world championship, Gilberto Parlotti had a fatal accident at the Isle of Man Tourist Trophy in 1972. The Morbidelli team was devastated by his loss but remained resolute and did not stop.": "Godine 1972, razvoj Morbidelli modela od 50cc je zaustavljen jer se trkačko odeljenje fokusiralo na klasu od 125cc. Gilberto Parloti je bio nezaustavljiv sa četiri uzastopne pobede, ali na vrhuncu njegovog napretka, Morbidelli tim je zadesila tragedija. Dok je vodio u svetskom šampionatu, Parloti je doživeo fatalnu nesreću na Isle of Man Tourist Trophy-ju. Tim je bio skrhan njegovim gubitkom, ali je ostao odlučan i nije odustao.",
  "Logo used by the Morbidelli racing team and other racing teams.": "Logo koji su koristili Morbidelli i drugi trkački timovi.",
  "Paolo Pileri (41) and Pier Paolo Bianchi (51) secured first and second place in the world championship, dominating the statistics. Of the 16 races in 1975, including those on the world circuit, the Morbidelli team achieved 15 podiums. The championship-winning preparation team included team owner Giancarlo Morbidelli, Jorg Möller, Giancarlo Cecchini, Giancarlo Bonaventura, and Franco Dionigi as mechanics. This Morbidelli team took first place in the constructors' championship against the world's top brands. Paolo Pileri and Pier Paolo Bianchi claimed first and second place in the world championship and, in reverse order, the Italian National Championship.": "Paolo Pileri i Pjer Paolo Bjanki osvojili su prvo i drugo mesto u svetskom šampionatu, u potpunosti dominirajući tom sezonom. Od ukupno 16 trka 1975. godine, Morbidelli tim je zabeležio čak 15 podijuma. Pobednički tim su činili vlasnik Đankarlo Morbideli, Jorg Meler, Đankarlo Čekini, Đankarlo Bonaventura i Franko Dionizi kao mehaničari. Ovaj tim je osvojio prvo mesto u šampionatu konstruktora, pobedivši najveće svetske brendove. Pileri i Bjanki su uzeli prva dva mesta u svetu, i obrnuto na italijanskom nacionalnom šampionatu.",
  "In late 1975, Giancarlo Morbidelli, Paolo Benelli, and Innocenzo Nardi Dei (Benelli Armi) joined forces to establish a company to mass-produce a replica of the 1975 world-champion Morbidelli 125 and sell it to private teams. This partnership between Giancarlo Morbidelli and the former Benelli Reparto Corse was named MBA, an acronym for Morbidelli Benelli Armi.": "Krajem 1975. godine, Đankarlo Morbideli, Paolo Beneli i Inočenco Nardi Dei (Benelli Armi) udružili su snage kako bi osnovali kompaniju za serijsku proizvodnju replike pobedničkog Morbidelli 125 modela i njegovu prodaju privatnim timovima. Ovo partnerstvo dobilo je ime MBA – akronim za Morbidelli Benelli Armi.",
  "The MBA VR 125 was initially manufactured at Benelli Armi's facility in Urbino but later moved to Sant Angelo in Vado in the province of Pesaro-Urbino. This union of two sporting powerhouses would bring more glory and history in the near future.": "MBA VR 125 se prvobitno proizvodio u pogonima Benelli Armi u Urbinu, da bi se kasnije proizvodnja preselila u Sant Angelo in Vado. Ovaj spoj dva velika sportska imena doneće još više slave i ispisati istoriju u godinama koje dolaze.",
  "Pier Paolo Bianchi became the world champion in the 125cc category with the Morbidelli MBA VR125, dominating the statistics just like in 1975. This marked Morbidelli's second world championship. The Morbidelli MBA team secured podium finishes in all nine Grand Prix races, with Pier Paolo Bianchi winning seven of them. For the second consecutive year, Morbidelli won the constructors' championship, Pier Paolo Bianchi became world champion, and Paolo Pileri secured 3rd place in the world championship.": "Pjer Paolo Bjanki postaje svetski šampion u klasi 125cc na Morbidelli MBA VR125, dominirajući sezonom kao i 1975. To je bila druga titula svetskog šampiona za Morbidelli. Tim je obezbedio podijum na svih devet Grand Prix trka, pri čemu je Bjanki pobedio na sedam. Drugu godinu zaredom, Morbidelli je osvojio šampionat konstruktora, Bjanki je postao šampion, a Paolo Pileri je zauzeo 3. mesto na svetu.",
  "Meanwhile, Giancarlo Morbidelli is promoting the creation of the new Morbidelli 250cc and 350cc in his workshops. This development was promoted by Giancarlo based on the 42hp of the 125 improving to 62hp at almost 12,000 rpm with 250cc. The first Morbidelli 250s began to compete and with the help of Pileri and Bianchi achieved six podiums in total and a 2nd place in the Belgian Grand Prix. On August 8, 1976, multiple world champion Giacomo Agostini was invited by Giancarlo Morbidelli to race in the Morbidelli 250 and he achieved a 2nd place in Misano.": "U međuvremenu, Đankarlo Morbideli podstiče razvoj novih modela od 250cc i 350cc u svojim radionicama. Razvoj je vođen logikom prelaska sa 42 KS na 125cc, na snažnijih 62 KS pri 12.000 obrtaja na 250cc. Prvi Morbidelli 250 modeli ubrzo su počeli da se takmiče i uz pomoć Pilerija i Bjankija ostvarili šest podijuma i 2. mesto na Velikoj nagradi Belgije. Višestruki svetski šampion Đakomo Agostini je 8. avgusta 1976. vozeći Morbidelli 250 osvojio drugo mesto u Misanu.",
  "In the second year of the Morbidelli 250cc, Paolo Pileri was the only rider set to compete in the World Championship. Unfortunately, due to injuries from a fall, Pileri couldn't start and suggested that Giancarlo Morbidelli invite Mario Lega. Unexpectedly, Mario Lega delivered an exceptional performance, securing only one Grand Prix victory but consistently finishing in nearly all the races. In 1977, he became the world champion in the Morbidelli 250 and earned 3rd place in the constructors' standings.": "U drugoj godini za model od 250cc, Paolo Pileri je trebao da bude jedini vozač u Svetskom šampionatu. Nažalost, zbog povreda prilikom pada, Pileri nije mogao da započne sezonu i predložio je Marija Legu kao zamenu. Na iznenađenje mnogih, Lega je vozio neverovatno dobro, pobedio na samo jednoj trci, ali je konzistentno završavao skoro svaku trku na visokim pozicijama. Godine 1977. osvojio je svetsku titulu, dok je tim zauzeo 3. mesto u poretku konstruktora.",
  "At the end of 1977, Giancarlo Morbidelli decided to leave MBA as Paolo Benelli wanted to introduce small 50cc MBA mopeds to the Italian market. Giancarlo Morbidelli had enough responsibilities managing his woodworking machinery business and the Morbidelli racing team, with no interest in starting a motorcycle business. The MBA acronym remained, but instead of Morbidelli Benelli Armi, it now stood for Moto Benelli Armi.": "Krajem 1977. godine, Đankarlo Morbideli donosi odluku da napusti MBA jer je Paolo Beneli želeo da izbaci male mopede od 50cc na italijansko tržište. Đankarlo je već imao dovoljno obaveza oko svoje fabrike mašina za obradu drveta i trkačkog tima, i nije ga interesovao ulazak u komercijalnu prodaju. Akronim MBA je ostao, ali je sada umesto Morbidelli Benelli Armi značio Moto Benelli Armi.",
  "Earlier this year, Giancarlo Morbidelli introduced his final masterpiece for racing: the incredible Morbidelli 500cc, featuring four cylinders arranged in a box with rotary valves and a twin crankshaft. This engine produced a staggering 130 horsepower at 11,500 rpm. The first version had a tubular frame, but the 500cc's raw power required a monocoque aluminum frame, with the fuel tank integrated into it and the engine hanging beneath.": "Ranije te godine, Đankarlo Morbideli je predstavio svoje poslednje trkačko remek-delo: neverovatni Morbidelli 500cc, sa četvorocilindričnim 'box' motorom, rotacionim ventilima i dvostrukom radilicom. Agregat je razvijao zapanjujućih 130 konjskih snaga na 11.500 obrtaja. Prva verzija je imala cevasti ram, ali je zbog sirove snage vrlo brzo napravljen aluminijumski 'monocoque' ram, sa rezervoarom integrisanim unutar rama.",
  "The entry of the Pesaro rider named Graziano Rossi marked a new era. Having just become the father of a future legend named Valentino, he found inspiration and managed to secure three Grand Prix victories and two more podium finishes with the Morbidelli 250cc. Despite various challenges, Graziano Rossi scored 67 points compared to Ballington's 141 and finished '79 with a well-deserved third place. Giancarlo Morbidelli focused entirely on the 500cc, forming a team with Graziano Rossi and Giovanni Pelletier from Rome.": "Dolazak vozača iz Pezara, Gracijana Rosija, označio je početak nove ere. Gracijano, koji je baš tada postao otac buduće legende Valentina Rosija, vozio je briljantno i osvojio tri pobede uz još dva podijuma u klasi 250cc. Uprkos brojnim izazovima, Rosi je završio sezonu 1979. na sjajnom trećem mestu. Đankarlo Morbideli je nakon ovoga svoj potpuni fokus prebacio na klasu 500cc i oformio tim sa Gracijanom Rosijem i Đovanijem Peletjeom.",
  "Morbidelli returned to his passion and delighted two-wheel enthusiasts with his new masterpiece: an incredible Morbidelli 850cc with a V8 engine and design by Pininfarina. This sport-touring model showcased the incredible engine that achieved 120 horsepower at 11,000 rpm. Only four units were made due to its exorbitant cost.": "Morbideli se vratio svojoj prvoj strasti i obradovao ljubitelje dvotočkaša još jednim remek-delom: neverovatnim Morbidelli 850cc modelom sa V8 motorom koji je dizajnirao Pininfarina. Ovaj 'sport-touring' model pokazao je neverovatne mogućnosti, isporučujući 120 KS na 11.000 obrtaja. Zbog neverovatno visokih troškova proizvodnje, napravljena su samo četiri primerka.",
  "Having established a museum with over 400 historic motorcycles and the largest collection of racing machines, Giancarlo Morbidelli focused on developing a V12 motorcycle. Time wasn't on his side to complete it, although the engine was in the final stages. In early 2020, at the age of 85, Giancarlo Morbidelli passed away, leaving behind legends, stories, and records worthy of a Hollywood film.": "Nakon što je otvorio muzej sa preko 400 istorijskih motocikala i najvećom kolekcijom trkačkih mašina, Đankarlo Morbideli je radio na razvoju svog V12 motora. Nažalost, nije mu preostalo dovoljno vremena da ga završi, iako je projekat bio u završnoj fazi. Početkom 2020. godine, u 85. godini života, Đankarlo nas je napustio, ostavljajući iza sebe legende, anegdote i rekorde dostojne holivudskih filmova.",
  "In 2021, MBP was founded in Bologna, Italy.": "Godine 2021. osnovan je MBP u Bolonji, Italija.",
  "MBP Moto S.r.l. was founded in 2021 with capital from the Keeway Group, with the aim and vision of continuing the legendary and iconic motorcycling legacy left by its founder, Giancarlo Morbidelli. Strategically choosing Bologna as its headquarters, MBP began establishing operations and initiating its brand acquisition process.": "MBP Moto S.r.l. je osnovan 2021. godine pod okriljem Keeway Group-e, sa jasnom vizijom da nastavi veliko nasleđe koje je ostavio Đankarlo Morbideli. Strateški pozicioniran u Bolonji, MBP je odmah započeo proces oživljavanja legendarnog brenda.",
  "At EICMA 2022, MBP Moto unveiled a series of prototypes that redefined motorcycle design, instantly capturing the attention of the global motorcycling community. Their innovative and striking designs at this event established MBP Moto as a trailblazer, earning widespread acclaim and setting new standards in the industry. In the same year, sales began for the first motorcycles under the MBP emblem, the M502N and C1002V.": "Na EICMA sajmu 2022. godine, MBP Moto je predstavio seriju prototipova koji su momentalno privukli pažnju svetske moto javnosti. Inovativan dizajn postavio je nove standarde i dokazao ozbiljne namere brenda. Iste te godine, započela je prodaja prvih motocikala pod oznakom MBP – modela M502N i C1002V.",
  "At EICMA 2023, MBP Moto unveiled its new prototypes, its HYPEVISION electric concept, and the 2024 lineup of models. The brand has gradually expanded its sales presence in China, Italy, and Spain, where the Keeway Group's main offices operate.": "Već na EICMA sajmu 2023., MBP Moto je predstavio svoj električni koncept HYPEVISION i potpunu liniju modela za 2024. godinu. Brend je nastavio snažnu ekspanziju i počeo prodaju širom Kine, Italije i Španije.",
  "After the Keeway Group acquired the brand, MBP was renamed and introduced the new Morbidelli emblem, inspired by its rich racing heritage. The black background symbolizes sophistication and elegance, while the white accents highlight speed and precision. \\\"MORBIDELLI\\\" arcs around the central circle like a beacon of the brand's heritage and its drive into the future.": "Nakon što je Keeway Grupa preuzela vlasništvo nad brendom, ime je promenjeno nazad u Morbidelli i predstavljen je novi, modernizovani logo inspirisan bogatim trkačkim nasleđem. Crna pozadina asocira na eleganciju, dok beli detalji simbolizuju brzinu i preciznost. Ime \\\"MORBIDELLI\\\" obuhvata centralni krug kao omaž prošlosti i jasna vizija budućnosti.",
  "Crowning the emblem, the laurel leaves represent a legacy of glory and triumph, paying homage to Morbidelli's distinguished racing past while reaffirming a commitment to excellence. Vibrant red symbolizes passion, while blue infuses Morbidelli's spirit into our motorcycles, apparel, and showrooms, all pulsing with the energy of competition.": "Lovorov venac na vrhu logotipa predstavlja trijumf i odaje počast impresivnoj trkačkoj istoriji brenda. Jarko crvena boja simbolizuje italijansku strast, dok plava unosi Morbidelli trkački DNK u današnje motocikle, opremu i salone.",
  "“BEYOND THE RIDE”": "“BEYOND THE RIDE”",
  "It's more than just a slogan—it's the heart of a brand where craftsmanship merges with the thrill of the journey. It's about the joy of riding a motorcycle, the bond between rider and road, and the legacy of performance and Italian racing spirit. Morbidelli isn't just about motorcycles; it's about the experiences and adventures they bring to life. This slogan invites riders to join a story of passion, freedom, and the art of motorcycling with every turn.": "To je mnogo više od slogana — to je srž brenda gde se inženjering spaja sa čistim uzbuđenjem vožnje. Predstavlja pravu radost vožnje, vezu između motocikliste i puta, i beskompromisni italijanski trkački duh. Morbidelli nisu samo motocikli; to su iskustva i avanture koje oni donose u život svakog vozača. Ovaj slogan vas poziva da i vi postanete deo priče o strasti, slobodi i vrhunskoj umetnosti vožnje na dva točka.",
  "Welcome to being part of the story!": "Dobrodošli i postanite deo priče!"
};

let content = fs.readFileSync('./app/about/content.ts', 'utf8');

for (const [en, sr] of Object.entries(translations)) {
  content = content.replace(en, sr);
}

// Adjust images:
// 1. Giancarlo Morbidelli (2nd image requested, which is morbidelli-giancarlo.png)
content = content.replace(
  /<img src=\\"\/photos\/history\/morbidelli-giancarlo\.png\\"[^>]*>/g,
  (match) => {
    return match.replace('class=\\"', 'style=\\"object-position: 50% 25%;\\" class=\\"');
  }
);

// 2. 1969 image (4th image requested, morbidelli-1969-bike.png)
content = content.replace(
  /<img src=\\"\/photos\/history\/morbidelli-1969-bike\.png\\"[^>]*>/g,
  (match) => {
    return match.replace('class=\\"', 'style=\\"object-position: 50% 25%;\\" class=\\"');
  }
);

// 3. 2020 image
content = content.replace(
  /<img src=\\"\/photos\/history\/morbidelli-2020-bike\.png\\"[^>]*>/g,
  (match) => {
    return match.replace('class=\\"', 'style=\\"object-position: 50% 25%;\\" class=\\"');
  }
);

fs.writeFileSync('./app/about/content.ts', content, 'utf8');
console.log('Update successful');
