const fs = require('fs');

const translations = {
  "Giancarlo Morbidelli was born to a family of farmers on October 18, 1934, in Pesaro, Italy. He grew up in an environment where neighbors Benelli and Motobi made history, not only in development but also in competition with their Reparto Corse. His first motorcycle was an Alpino, which he modified with limited resources to achieve better performance. Following his father's suggestion, Giancarlo trained at a technical woodworking school, as there were many furniture companies in Pesaro and nearby, making it likely he could find work as a skilled carpenter.": "Đankarlo Morbideli rođen je u seljačkoj porodici 18. oktobra 1934. godine u Pezaru, Italija. Odrastao je u okruženju u kom su njegove komšije iz kompanija Benelli i Motobi ispisivale istoriju, ne samo u razvoju motocikala već i u takmičenjima kroz svoja trkačka odeljenja. Njegov prvi motocikl bio je Alpino, koji je samostalno modifikovao sa vrlo malo resursa kako bi izvukao bolje performanse. Na očev nagovor, Đankarlo je upisao tehničku školu za obradu drveta jer je u Pezaru i okolini bilo mnogo industrije nameštaja, pa su šanse za zaposlenje bile velike.",
  "In 1959, at just 25, he founded his own company, Morbidelli woodworking Machines, developing, manufacturing, and selling woodworking machinery. With his mechanical expertise and business acumen, he built a thriving company in Pesaro over 15 years, with over 350 employees and sales in more than 60 countries. However, Giancarlo had boundless energy, and in addition to running his company, he knew how to pursue his greatest passion: motorcycles.": "Već 1959. godine, sa samo 25 godina, osnovao je sopstvenu firmu za razvoj, proizvodnju i prodaju mašina za obradu drveta – Morbidelli Woodworking Machines. Spojivši inženjersko znanje i njuh za biznis, tokom 15 godina izgradio je izuzetno uspešnu kompaniju u Pezaru koja je brojala preko 350 zaposlenih i izvozila u više od 60 zemalja širom sveta. Međutim, Đankarlova energija je bila neograničena, pa je pored vođenja kompanije našao vremena da se posveti svojoj najvećoj strasti: motociklima.",
  "The first Morbidelli motorcycle was a 60cc model based on a Benelli engine with a modified cylinder and cylinder head, placed in a Bianchi Falco Supersport frame. This bike was ridden by Enzo Lazzarini in the local Cadet races. The first internal Morbidelli racing team, from left to right, included the new technician Sergio Grassini, the young rider Franco Ringhini, Giancarlo Morbidelli, and rider Eugenio Lazzarini. In 1968, they officially began competing for Reparto Corse.": "Prvi Morbidelli motocikl bio je model od 60cc baziran na Benelli agregatu sa modifikovanim cilindrom i glavom, smešten u ram od Bianchi Falco Supersport-a. Ovaj motocikl je vozio Enco Lazarini na lokalnim 'Cadet' trkama. Prvi interni trkački tim Morbidelli činili su (s leva na desno): novi tehničar Serđo Grasini, mladi vozač Franko Ringini, Đankarlo Morbideli i vozač Euđenio Lazarini. Godine 1968. zvanično su počeli da se takmiče kao deo trkačkog odeljenja (Reparto Corse).",
  "Ringhini and Lazzarini successfully competed in several races with the Morbidelli 50cc, finishing first and second at the Slovenian Grand Prix, and also winning the Italian Championship. This first international victory motivated Morbidelli to create the Morbidelli 125cc, leading them to begin developing a twin-cylinder engine to compete in the 1970 World Championship.": "Ringini i Lazarini su veoma uspešno vozili Morbidelli 50cc na nekoliko trka, osvojivši prvo i drugo mesto na Velikoj nagradi Slovenije, a pobedili su i na prvenstvu Italije. Ova prva internacionalna pobeda je motivisala Morbidelija da napravi model od 125cc, zbog čega su započeli razvoj potpuno novog dvocilindričnog agregata za takmičenje u Svetskom šampionatu 1970. godine.",
  "The first official logo used by the Morbidelli racing team.": "Prvi zvanični logo koji je koristio Morbidelli trkački tim.",
  "The Morbidelli team in the 50cc category was established and achieved five podiums out of eight races with Lazzarini and Ringhini. Giancarlo Morbidelli recruited Gilberto Parlotti, who had previously raced the Benelli 250 four-cylinder to help Kel Carruthers win the world championship for Benelli in 1969, to join the 125cc category. In his first year, Parlotti secured three victories: one in the world championship and two in national races. The world championship began in 1970 with Franco Ringhini as a rider and, starting with the Czech Grand Prix, with Gilberto Parlotti (10).": "Morbidelli tim u klasi 50cc se čvrsto etablirao ostvarivši pet podijuma iz osam trka sa Lazarinijem i Ringinijem. U klasu od 125cc Đankarlo Morbideli je doveo Gilberta Parlotija, koji je prethodno vozio četvorocilindrični Benelli 250 i pomogao Kelu Karadersu da osvoji svetski šampionat za Benelli 1969. U svojoj prvoj godini, Parloti je obezbedio tri pobede: jednu u svetskom šampionatu i dve na nacionalnim trkama. Svetski šampionat 1970. godine započeo je Franko Ringini, a od Velike nagrade Češke mu se pridružio i Gilberto Parloti (10).",
  "Winning two national races, followed by two second places in the Austrian and German Grand Prix, Parlotti won the Nations Grand Prix in Monza, establishing himself as Morbidelli's top rider. That year, Gilberto Parlotti achieved eighth place in the world championship. Meanwhile, with four victories in the 50cc Italian Championship, Alberto Leva from Rome (104) earned the first star for the Morbidelli team by becoming the 50cc Italian Champion on a Morbidelli.": "Nakon dve pobede na nacionalnim trkama i dva druga mesta na Velikim nagradama Austrije i Nemačke, Parloti je odneo pobedu i na Gran priju Nacija u Monci, cementiravši svoju poziciju prvog vozača tima. Te godine je završio na osmom mestu u generalnom plasmanu svetskog šampionata. U međuvremenu, sa četiri pobede u prvenstvu Italije u klasi 50cc, Alberto Leva iz Rima (104) doneo je Morbidelli timu prvu veliku titulu postavši šampion Italije."
};

let content = fs.readFileSync('./app/about/content.ts', 'utf8');

for (const [en, sr] of Object.entries(translations)) {
  content = content.replace(en, sr);
}

fs.writeFileSync('./app/about/content.ts', content, 'utf8');
console.log('Update successful');
